"""add owner_id to heroes

Revision ID: 4733a4dd6da9
Revises: 91807f3de5be
Create Date: 2026-09-05 14:13:28.823963

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4733a4dd6da9"
down_revision: str | Sequence[str] | None = "91807f3de5be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Existing rows have no owner to backfill -- Hero has never carried an owner
    # concept before this migration, so there's no real value to assign them.
    # Only ever affects this template's own disposable example data (heroes
    # created against a devcontainer/mock/test stack), never a forked app's real
    # data, since no fork of this template could have shipped owner-scoped Hero
    # rows before this migration existed.
    op.execute("DELETE FROM heroes")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("heroes", sa.Column("owner_id", sa.String(), nullable=False))
    op.create_index(op.f("ix_heroes_owner_id"), "heroes", ["owner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_heroes_owner_id"), table_name="heroes")
    op.drop_column("heroes", "owner_id")
    # ### end Alembic commands ###
