"""add created_at/updated_at to heroes

Revision ID: 7dc8146fcf6c
Revises: 383b0a85de69
Create Date: 2026-09-03 22:45:07.749456

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7dc8146fcf6c"
down_revision: str | Sequence[str] | None = "383b0a85de69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "heroes",
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    op.add_column(
        "heroes",
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("heroes", "updated_at")
    op.drop_column("heroes", "created_at")
    # ### end Alembic commands ###
