"""add record-lifecycle mixins and revisions table

Revision ID: 8e0846bd353a
Revises: 4733a4dd6da9
Create Date: 2026-09-05 14:49:34.292415

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e0846bd353a"
down_revision: str | Sequence[str] | None = "4733a4dd6da9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "revisions",
        sa.Column("resource", sa.String(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_revisions_record_id"), "revisions", ["record_id"], unique=False)
    op.create_index(op.f("ix_revisions_resource"), "revisions", ["resource"], unique=False)
    op.add_column("heroes", sa.Column("archived_at", sa.DateTime(), nullable=True))
    # server_default backfills any existing row (this template's own disposable
    # example data) -- the model itself only declares a client-side `default`
    # (see app.models.mixins.Draftable/Lockable), matching every other plain
    # column here; the server_default stays in place afterward as a harmless
    # extra safety net, not removed in a follow-up statement.
    op.add_column(
        "heroes", sa.Column("is_draft", sa.Boolean(), nullable=False, server_default=sa.true())
    )
    op.add_column("heroes", sa.Column("publish_at", sa.DateTime(), nullable=True))
    op.add_column("heroes", sa.Column("unpublish_at", sa.DateTime(), nullable=True))
    op.add_column(
        "heroes", sa.Column("is_locked", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.alter_column("heroes", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("heroes", "powers", existing_type=postgresql.ARRAY(sa.VARCHAR()), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "heroes", "powers", existing_type=postgresql.ARRAY(sa.VARCHAR()), nullable=False
    )
    op.alter_column("heroes", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("heroes", "is_locked")
    op.drop_column("heroes", "unpublish_at")
    op.drop_column("heroes", "publish_at")
    op.drop_column("heroes", "is_draft")
    op.drop_column("heroes", "archived_at")
    op.drop_index(op.f("ix_revisions_resource"), table_name="revisions")
    op.drop_index(op.f("ix_revisions_record_id"), table_name="revisions")
    op.drop_table("revisions")
    # ### end Alembic commands ###
